name: MonoKickstart Ci
on: [push]
jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-20.04, macos-13, macos-14]
    name: Steam Runtime
    runs-on: ${{ matrix.os }}
    container: registry.gitlab.steamos.cloud/steamrt/sniper/sdk:beta
    steps:
      - uses: actions/checkout@v4
        with:
            submodules: true
            path: monokickstart

      - name: Install Depdencies
        if: runner.os == 'Linux'
        run: sudo apt update && sudo apt install libgif-dev autoconf libtool automake build-essential gettext libglib2.0-dev libcairo2-dev libtiff-dev libexif-dev ninja-build mono-complete -y
      
      - name: Install Depdencies
        if: runner.os == 'macOS'
        run: brew install glib cairo libexif libjpeg giflib libtiff autoconf libtool automake pango pkg-config cmake ninja && brew link gettext --force
      
      - name: Build mono
        run: |
            git clone https://gitlab.winehq.org/mono/mono --depth=1 --recursive --shallow-submodules
            cd mono
            git apply -v ../monokickstart/patches/mono*
            cd external/corefx
            git apply -v ../../../monokickstart/patches/corefx*
            cd ../corert
            git apply -v ../../../monokickstart/patches/corert*
            cd ../.. 
            ./autogen.sh --with-ikvm-native=no
            make -j${nproc}
            
      - name: Upload libMonoPosixHelper Artifact
        if: runner.os == 'Linux'
        uses: actions/upload-artifact@v4
        with:
            name: libMonoPosixHelper
            path: mono/support/.libs/libMonoPosixHelper.so
            
      - name: Upload libMonoPosixHelper Artifact
        if: runner.os == 'macOS'
        uses: actions/upload-artifact@v4
        with:
            name: libMonoPosixHelper
            path: mono/support/.libs/libMonoPosixHelper.dylib
            
      - name: Upload net_4_x-linux Artifact
        if: runner.os == 'Linux'
        uses: actions/upload-artifact@v4
        with:
            name: net_4_x-linux
            path: mono/mcs/class/lib/net_4_x-linux/

      - name: Upload net_4_x-macOS Artifact
        if: runner.os == 'macOS'
        uses: actions/upload-artifact@v4
        with:
            name: net_4_x-linux
            path: mono/mcs/class/lib/net_4_x-macos/

      - name: Build libgdiplus
        run: |
            git clone https://gitlab.winehq.org/mono/libgdiplus --depth=1 --recursive --shallow-submodules
            cd libgdiplus
            ./autogen.sh
            make -j${nproc}
            if [ "$RUNNER_OS" == "Linux" ]; then
              cp src/.libs/libgdiplus.so.0.0.0 ../libgdiplus.so.0
            fi
        shell: bash

      - name: Upload libgdiplus Artifact
        uses: actions/upload-artifact@v4
        with:
            name: libgdiplus
            path: libgdiplus.so.0

            
      - name: Upload libgdiplus Artifact
        if: runner.os == 'macOS'
        uses: actions/upload-artifact@v4
        with:
            name: libgdiplus
            path: libgdiplus/src/.libs/libgdiplus.*.dylib


      - name: Build MonoKickstart
        run: |
            cd monokickstart
            cmake -B build -D CMAKE_BUILD_TYPE=Release -G Ninja
            cmake --build build --parallel
            cd ..
            mkdir artifact
            cp monokickstart/build/kick.bin.x86_64 \
            monokickstart/precompiled/monoconfig \
            monokickstart/precompiled/monomachineconfig \
            mono/mcs/class/lib/net_4_x-linux/Mono.Posix.dll \
            mono/mcs/class/lib/net_4_x-linux/Mono.Security.dll \
            mono/mcs/class/lib/net_4_x-linux/System.Configuration.dll \
            mono/mcs/class/lib/net_4_x-linux/System.Core.dll \
            mono/mcs/class/lib/net_4_x-linux/System.Data.dll \
            mono/mcs/class/lib/net_4_x-linux/System.Drawing.dll \
            mono/mcs/class/lib/net_4_x-linux/System.Numerics.dll \
            mono/mcs/class/lib/net_4_x-linux/System.Runtime.Serialization.dll \
            mono/mcs/class/lib/net_4_x-linux/System.Security.dll \
            mono/mcs/class/lib/net_4_x-linux/System.Xml.Linq.dll \
            mono/mcs/class/lib/net_4_x-linux/System.Xml.dll \
            mono/mcs/class/lib/net_4_x-linux/System.dll \
            mono/mcs/class/lib/net_4_x-linux/mscorlib.dll \
            artifact

      - name: Upload kick.bin.x86_64 Artifact
        uses: actions/upload-artifact@v4
        with:
            name: kick.bin.x86_64
            path: artifact/*
            
              

      
