name: MonoKickstart Ci
on: [push]
jobs:
  build:
    name: Rocky Linux
    runs-on: ubuntu-20.04
    # TODO: Run on Rocky Linux, using buntu right now because I haven't checked the package names on RHEL yet
    steps:
      - name: Build libgdiplus
        run: |
            sudo apt-get install libgif-dev autoconf libtool automake build-essential gettext libglib2.0-dev libcairo2-dev libtiff-dev libexif-dev ninja-build mono-complete
            git clone https://gitlab.winehq.org/mono/libgdiplus --depth=1 --recursive --shallow-submodules
            cd libgdiplus
            ./autogen.sh
            make -j${nproc}

      - name: Upload libgdiplus Artifact
        uses: actions/upload-artifact@v4
        with:
            name: libgdiplus
            path: libgdiplus/src/.libs/libgdiplus.so*

      - name: Build mono
        run: |
            git clone https://gitlab.winehq.org/mono/mono --depth=1 --recursive --shallow-submodules
            cd mono
            ./autogen.sh
            make -j${nproc}

      - name: Upload libgdiplus Artifact
        uses: actions/upload-artifact@v4
        with:
            name: libMonoPosixHelper
            path: mono/support/.libs/libMonoPosixHelper.so

      - uses: actions/checkout@v4
        with:
            submodules: true
            path: monokickstart

      - name: Build MonoKickstart
        run: |
            cd monokickstart
            cmake -B build -D CMAKE_BUILD_TYPE=Release -G Ninja
            cmake --build build --parallel
            ls build/

      